import { VisuallyHidden } from '@spark-web/a11y';
import { Box } from '@spark-web/box';
import { Button, ButtonLink } from '@spark-web/button';
import { Container } from '@spark-web/container';
import { Divider } from '@spark-web/divider';
import { Field } from '@spark-web/field';
import { Heading } from '@spark-web/heading';
import { CheckCircleIcon, PhoneIcon } from '@spark-web/icon';
import { Inline } from '@spark-web/inline';
import { Link } from '@spark-web/link';
import { ContentDialog } from '@spark-web/modal-dialog';
import { Row } from '@spark-web/row';
import { Stack } from '@spark-web/stack';
import { Text } from '@spark-web/text';
import { TextInput } from '@spark-web/text-input';
import { TextList } from '@spark-web/text-list';
import { useDisclosure } from '@spark-web/utils';
import type { NextPage } from 'next';
import NextHead from 'next/head';
import { useState } from 'react';

import { Logo } from '../components/logo';

const Home: NextPage = () => {
  const { isOpen, onOpen, onToggle } = useDisclosure();
  const [postCode, setPostCode] = useState('');

  return (
    <div>
      <NextHead>
        <title>Basic Example App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </NextHead>

      <main>
        <Box
          as="header"
          position="sticky"
          top={0}
          zIndex="sticky"
          background="surface"
        >
          <Container size="xlarge">
            <Inline width="full" gap="large" alignY="center" padding="medium">
              <Link href="/">
                <VisuallyHidden>Brighte</VisuallyHidden>
                <Logo />
              </Link>
              <Box flex={1} justifyContent="center">
                <Heading level="3" align="center">
                  Basic Example App
                </Heading>
              </Box>
              <ButtonLink
                size="large"
                tone="neutral"
                href="https://spark.brighte.com.au/"
              >
                <PhoneIcon size="xsmall" /> Need help?
              </ButtonLink>
            </Inline>
          </Container>
          <Divider />
        </Box>

        <Container>
          <Stack gap="xlarge" padding="xlarge">
            <Heading level="1">Basic Example App for @spark-web</Heading>

            <Stack
              as="form"
              gap="xlarge"
              borderRadius="medium"
              border="standard"
              padding="xlarge"
              onSubmit={(event: React.FormEvent<HTMLFormElement>) => {
                event.preventDefault();

                // We should probably do some sort of server roundtrip here,
                // but for now we're just going to pop the modal anyway.

                // There should also be form validation etc.

                // At Brighte we generally use React Hook Form for this,
                // please see a separate example of that.

                onOpen();
              }}
            >
              <Heading level="2">The future is Brighte</Heading>

              <Text>
                We help finance your solar with zero upfront costs and 0%
                interest - and no nasty catches.
              </Text>

              <TextList icon={<CheckCircleIcon size="xsmall" />}>
                <Text>See your neighbour&apos;s solar uptake</Text>
                <Text>Compare solar costs & see what size you might need</Text>
                <Text>Get up to 3 quotes & pay with Brighte</Text>
              </TextList>

              <Row gap="medium" alignY="bottom">
                <Field label="Post code or suburb">
                  <TextInput
                    value={postCode}
                    onChange={event => setPostCode(event.target.value)}
                  />
                </Field>
                <Button type="submit">Start here</Button>
              </Row>
            </Stack>

            <Text>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Optio
              nostrum consectetur, similique cumque quam voluptatibus veniam
              officiis nesciunt deleniti sequi, architecto a fugiat ipsum.
              Perspiciatis quisquam eius saepe quam omnis.
            </Text>
          </Stack>
        </Container>
      </main>

      <ContentDialog
        title="Title"
        description="Controlled example"
        isOpen={isOpen}
        onToggle={onToggle}
      >
        <Text>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consequatur
          optio molestiae dolorem qui omnis reiciendis dignissimos numquam
          aperiam, rem natus, totam, repudiandae cum voluptatibus quos? Dicta,
          odio! Accusantium, reiciendis quidem.
        </Text>
      </ContentDialog>
    </div>
  );
};

export default Home;
